---
title: "Introduction"
description: | 
  Presentation of the thesis
  
author:
  - name: Plasman Héloïse
    url: {http://Heloise04.github.io/Heloise_blog/}
date: 11-27-2020
categories:
  - "English for Science"
output:
  distill::distill_article:
    self_contained: false
---

# Introduction 
In the English course and in collaboration with the SDD course given in the 2nd Bachelor of Biology, we were asked to choose a scientific, mathematical or computer science theme that we like and to create a blog on it.

In this context, I chose as my thesis "Humans and Technology, Is It a Good or a Bad Thing?".

This topic seemed topical to me because we are in a society, in an era where everything seems to go faster and faster, more and more computerized, where technology is omnipresent and seems impossible to live without. The question to be asked therefore is “How far technology can go and especially where is the limit between benefits and disadvantages or even danger?”.

Moreover, I use, myself, technologies in my everyday life. I think, I am normally in front of à screen 10 hours per day and a lot more since the pandemic started. I think since then I wake up with my computer and I go bed with my cell phone. I don’t think it’s a big deal for my because since mid-secondary it’s my way to study but that doesn't mean that I don't sometimes feel the drawbacks of these “screen technology” : itchy eyes when it’s time to go to bed (10:30-11 pm) and sometimes little headaches.


__*But at the end what really is technology ?*__

According to the Larousse definition, technology is : *The study or the set of tools, machines, processes, knowledge and methods used in a certain technical field.* Which means that technology is found in all kinds of fields, in our everyday life and has effects at all levels of our lifestyle.

This is why on this blog, I will try to cover various aspects of technology but I will not be doing all of them because this word takes in an immensity of fields of application.
Here is a list of some fields of application that I would like to cover :

* A hyper-connected world (WiFi, 5G, smartphones,...)
* Artificial intelligence (AI)
* nanotechnologies (which affect many more fields than one might think)
* Always more feats in medicine and health
* Everyday habits (batteries, electricity,...)
* Environnement  
* …
