---
title: "Article 2 : Tech Tent : Will better batteries persuade us to go electric?"
description: |
  Improvement in batteries 
author:
  - name: Plasman Héloïse
    url: {http://Heloise04.github.io/Heloise_blog/}
date: 11-22-2020
preview: 
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

_Source of the article_ : BBC News

_Word count_ : 496

_URL_ : https://www.bbc.com/news/technology-55016147


## Summary 
In this article, we talk about the fact that we are going to improve batteries more and more so that they are better, safer, lighter, charge faster, store more,...

This improvement will make it possible to see electric motorization in a different way, even if we have to keep in mind to really have an ecological impact, it's our whole way of life that must be changed : keep the car for short trips and take other types of transport for the longest ones and even if there are no or less emissions during the use, the production, it generally produces much more emissions.
In addition, thanks to these progresses, we are trying to provide electricity to rural Kenya using renewable energies.


## Vocabulary: 

| Words from the text 	| Synonym / explanation in English 	|
|:-------------------:	|:--------------------------------:	|
|tampering|the action of touching or making changes to something that you should not, usually when you are trying to damage it or do something illegal. In this contest = change|
|leap|to achieve something suddenly, usually fame, power, or importance|
|renewable energy|energy that is produced using the sun, wind, etc., or from crops, rather than using fuels such as oil or coal|
|grid|a system of wires through which electricity is connected to different power stations across a region|


## Analysis table about the study


#### *Researchers ?*
* Elon Musk
* Colin Herron : automotive engineer
* Wangari Muchiri : renewable energy engineer


#### *Published in ? when (if mentioned) ?*
BBC News
20^th Novembre 2020


#### *General topic*
* Batteries 
* Environnement and zero-carbon
* Ecology


#### *Procedure/ what was examined* 
* Improvement of batteries 
* Improvement of the Kenya's electricity grid dependent on renewable energy


#### *Conclusion / discovery* 
Within 4 or 5 years the improvement of the batteries will do a big jump. But we have to keep in mind that batteries may zero-carbon emission but that their production, themself do a lot of emission.

We are also trying to make all rural areas of Kenya self-sufficient in electricity thanks to renewable energy


#### *Remaining questions*
How far we can go ? 
