---
title: "Article 7 : 10 Ways Technology Is Changing Healthcare"
description: |
  Presentation of 10 ways technology has changed healthcare
author:
  - name: Plasman Héloïse
    url: {http://Heloise04.github.io/Heloise_blog/}
date: 03-14-2021
categories:
  - "English for Science"
  - "Articles"
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

_Source of the article_ : The Medical Futurist

_Word count_ : 2531

_URL_ : https://medicalfuturist.com/ten-ways-technology-changing-healthcare/#

## Summary 
The future of healthcare is shaping with advances in digital healthcare technologies, such as artificial intelligence, VR/AR, 3D-printing, robotics or nanotechnology ans many others. We have to familiarize with them and not be afraid of them because there are just there to help us, to improve our medicine and there will have zero problem if we control them. 


## Vocabulary: 

| Words from the text 	| Synonym / explanation in English 	| French translation |
|:-------------------:	|:--------------------------------:	|:----------------:	|
|dystopias|an imaginary place or state in which everything is extremely bad or unpleasant syn : utopia|dystopies|
|betterment|the process of becoming or making something/somebody better syn : improvement|amélioration|
|root|the main cause of something, such as a problem or difficult situation|origine, source|
|disrupting|to make it difficult for something to continue in the normal way|perturber|
|wielded|to have and use power, authority,…|manié|
|counterparts|a person or thing that has the same position or function as somebody/something else in a different place or situation|homologues|
|soothing|hat makes somebody who is anxious, upset,... feel calmer|apaisante|
|albeit|although|quoique, bien que|
|depictions|the act of showing what somebody/something is like in words or pictures, especially in a work of art|représentations|
|remotely|(usually in negative sentences)to a very slight degree
syn : slightly|à distance|
|almighty|having complete power|tout-puissant, omnipotent|
|figment|something that somebody has imagined and that does not really exist|invention|
|yoked|to join two animals together with a yoke; to attach an animal to something with a yoke|attelé, accouplé|
|leveraging|to get as much advantage or profit as possible from something that you have|tirer parti|
|wound|an injury to part of the body, especially one in which a hole is made in the skin using a weapon|plaie, blessure|


## Analysis table about the study

#### *Researchers ?*

* Atomwise 
*Google’s DeepMind
* Osso VR
* Immersive Touch
* Case Western Reserve University
* Magic Leap
* SyncThink
* XRHealth
* Brainlab
* MedWand
* BioIntelliSense
* Illumine 
* Habit 
* Turbine
* Recursion Pharmaceuticals
* Deep Genomics
* Virtual Physiological Human Institute
* Max Planck Institute
* MIT researchers
* Grapheal 
* Rensselaer Polytechnic Institute in Troy, New York
* NGO : Rufugee Open Ware and Not impossible

#### *Published in ? when (if mentioned) ?*

The Medical Futurist
3rd of March 2020


#### *General topic*

Application of technology in medicine and in healthcare in general

#### *Procedure/ what was examined* 

* Artificial intelligence
* Virtual reality
* Augmented reality
* Healthcare trackers, wearables and sensors
* Medical tricorder
* Genome sequencing
* Revolutionizing drug development 
* Nanotechnology
* Robotics
* 3D-printing

#### *Conclusion / discovery* 

Don’t’ be scared by technology, it has a lot of really good application and will help improve our medicine. 

#### *Remaining questions*

/
