---
title: "My English Activity Log : MEAL"
author:
  - name: "Plasman Héloïse" 
date: "`r Sys.Date()`"
categories:
  - "English for Science"
output: distill::distill_article
---

Here a few thing that I do and that I did in English during my life : 

* Since I'm 5 years old I pratice English at school because like I mention in the section "about me" I did an immersion school. 

* Since a long time I listen and watch to a lot of Youtube videos in English, it's often video about food and cooking because I love that. 

* I often read recipes in English to have the best recipe of the original dishes like pancakes,...

* I have already read 2 books in Engish. It was talking about Greeek Mythology and was writen by the same author as "Percy Jackson"

* Occasionally, I look movies in English, recently I was old disney movies like "Snow white"

* Time to time, I look some series in English, for the moment I watch "Sherlock Holmes" on Netflix first because it's only in Enghish but also because I wanted to hear the real voice of the principal actor (Benedict Cumberbatch)

* I always listen to music in English, there isn't a single day that I don't listen to it. 


Update : 04th of March 2021

* Still listening lots of music and sing even if I know that I'm a bad singer (hihi)

* Watch some crime series on Netflix (Valhalla)

* Watch some videos on Youtube 


Update : 14th of April 2021

Same as before
